name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "30 14 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
      read: user
    steps:
      - uses: actions/checkout@v4

      - name: Update README with WakaTime Simple Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECTION_NAME: "waka-simple"
          COMMIT_MESSAGE: "Updated simple waka stats section"
          SHOW_TIMEZONE: false
          SHOW_PROJECTS: false
          SHOW_LANGUAGE: true
          SHOW_OS: false
          SHOW_EDITORS: false
          SHOW_LINES_OF_CODE: false
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          LOCALE: en
